version: '3.8'

services:
  rendev-site:
    build: .
    container_name: rendev-website
    ports:
      - "8045:8045"
    restart: unless-stopped
    networks:
      - rendev-network

networks:
  rendev-network:
    driver: bridge
